baseURL = 'https://okunix.github.io/'
languageCode = 'en-us'
title = "okunix"

[menus]
  [[ menus.main ]]
  name = 'Home'
  pageRef = '/'
  weight = 10
  [[ menus.main ]]
  name = 'Blog'
  pageRef = '/blog/'
  weight = 20
  [[ menus.main ]]
  name = 'About'
  pageRef = '/about/'
  weight = 30
  [[ menus.main ]]
  name = 'Feed'
  pageRef = '/index.xml'
  weight = 40

[outputs]
  home = ['html', 'rss']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[services]
  [services.rss]
    limit = 20

[markup]
  [markup.highlight]
    style = 'tokyonight-moon'
