baseURL = 'https://cr78.gitlab.io/'
languageCode = 'en-us'
title = "yusuf's site"

[menus]
  [[ menus.main ]]
  name = 'Home'
  pageRef = '/'
  weight = 5
  [[ menus.main ]]
  name = 'Blog'
  pageRef = '/blog/'
  weight = 10
  [[ menus.main ]]
  name = 'About'
  pageRef = '/about/'
  weight = 20
  [[ menus.main ]]
  name = 'Feed'
  pageRef = '/blog/index.xml'
  weight = 30

[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[services]
  [services.rss]
    limit = 20

[markup]
  [markup.highlight]
    style = 'nordic'
