baseURL = 'https://cr78.gitlab.io/'
languageCode = 'en-us'
title = "Yusuf's Site"

[menus]
  [[ menus.main ]]
  name = 'About'
  pageRef = '/about/'
  weight = 10
  [[ menus.main ]]
  name = 'Blog'
  pageRef = '/blog/'
  weight = 20
  [[ menus.main ]]
  name = 'RSS'
  pageRef = '/index.xml'
  weight = 30
